//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     创建人：wms
//     创建时间：2019/12/11 16:10:48
//     说明：
// </auto-generated>
//------------------------------------------------------------------------------
using JadeFramework.Dapper;
using JadeFramework.Dapper.SqlGenerator;
using Rex.WorkFlow.Web.Repositories;
using Rex.WorkFlow.Web.Models;
using System.Data;

namespace Rex.WorkFlow.Web.Repositories.Impls
{
    /// <summary>
    /// 流程委托表 仓储
    /// </summary>
    public class WfWorkflowAssignRepository : DapperRepository<WfWorkflowAssign>, IWfWorkflowAssignRepository
    {
        public WfWorkflowAssignRepository(IDbConnection connection, SqlGeneratorConfig config) : base(connection, config)
        {
        }
    }
}

